# Generated by Django 3.1.13 on 2021-11-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insta_model',
            old_name='insta_url',
            new_name='instagram_url',
        ),
    ]
