# Generated by Django 3.1.13 on 2021-11-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0002_auto_20211120_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insta_model',
            old_name='instagram_url',
            new_name='insta_url',
        ),
    ]
