# Generated by Django 3.1.13 on 2021-11-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0003_auto_20211120_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='insta_ghost_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_url', models.CharField(max_length=500)),
            ],
        ),
    ]
